### ISSUE TITLE
Error: start must be string

### ISSUE THREAD

**Issue by Epoche-Napoleon** [jweiland-net/glossary2#52]
Following Error in TYPO3 10.4.26 and Glossary2 5.05

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1537277163: start must be string | InvalidArgumentException thrown in file /html/epochenapoleon/public/typo3/sysext/core/Classes/Routing/Aspect/StaticRangeMapper.php in line 77. Requested URL: https://composer.epoche-napoleon.net/werk/a/adelung.html
This is my config.yaml for the routing:
https://gist.github.com/Epoche-Napoleon/f714c4049a0a87d9cd729e31d8d88313

**Comment by Epoche-Napoleon** [comment]
Sorry the error isn

**Comment by Epoche-Napoleon** [comment]
Sorry a mistake of me. The Problem isn't closed.

**Comment by froemken** [comment]
Hello @Epoche-Napoleon 

this is not a problem of TYPO3 or glossary2.
You have chosen the wrong  abstract type for A-Z list here:
https://gist.github.com/Epoche-Napoleon/f714c4049a0a87d9cd729e31d8d88313#file-config-yaml-L90

Please use `StaticValueMapper` instead and the problem is solved ;-)

Have a cool start into this new week

Stefan
